egypt_locations_dict =  {
    'Abdeen': 'Abdeen',
    'Ain Shams': 'Ain Shams',
    'Zamalek': 'Zamalek',
    'Maadi': 'Maadi',
    'Heliopolis': 'Heliopolis',
    'Nasr City': 'Nasr City',
    'Mohandessin': 'Mohandessin',
    'Shubra': 'Shubra',
    'Dokki': 'Dokki',
    'Agouza': 'Agouza',
    'Masr El Gedida': 'Masr El Gedida',
    'Helwan': 'Helwan',
    'Manial': 'Manial',
    'Giza': 'Giza',
    'Zayed':'Zayed',
    'New Cairo': 'New Cairo',
    '15 May City': '15 May City',
    '6th of October City': '6th of October City',
    'Obour City': 'Obour City',
    'Badr City': 'Badr City',
    'Cairo': 'Cairo',
    'Alexandria': 'Alexandria',
    'Luxor': 'Luxor',
    'Aswan': 'Aswan',
    'Red Sea': 'Red Sea',
    'South Sinai': 'South Sinai',
    'Tanta': 'Gharbia',
    'Ismailia': 'Ismailia',
    'Mansoura': 'Dakahlia',
    'Suez': 'Suez',
    'Port Said': 'Port Said',
    'Assiut': 'Assiut',
    'Sohag': 'Sohag',
    'Qena': 'Qena',
    'Beni Suef': 'Beni Suef',
    'Faiyum': 'Faiyum',
    'Minya': 'Minya',
    'Damietta': 'Damietta',
    'Kafr El Sheikh': 'Kafr El Sheikh',
    'Imbaba': 'Imbaba',
    'Haram': 'Haram',
    'Boulaq': 'Boulaq',
    'Hawamdiya': 'Hawamdiya',
    'Kirdasa': 'Kirdasa',
    'Sheikh Zayed': 'Sheikh Zayed',
    'October City': 'October City',
    'Oseem': 'Oseem',
    'Badrasheen': 'Badrasheen',
    'Saf': 'Saf',
    'Atfih': 'Atfih',
    'Ayyat': 'Ayyat',
    'Abu Nomros': 'Abu Nomros',
    'Kafr Tohormos': 'Kafr Tohormos',
    'Nahia': 'Nahia',
    'Ashmun': 'Ashmun',
    'Kafr Badrasheen': 'Kafr Badrasheen',
    'Kafr Ghatati': 'Kafr Ghatati',
    'Kafr Hakim': 'Kafr Hakim',
    'Kafr Shokr': 'Kafr Shokr'
}