# Generated by Django 5.0.6 on 2024-10-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllVendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='-', max_length=150)),
                ('vendor_link', models.CharField(default='-', max_length=255)),
                ('vendor_description', models.CharField(default='-', max_length=255)),
                ('vendor_category', models.CharField(default='-', max_length=50)),
                ('vendor_locations', models.CharField(default='-', max_length=255)),
                ('vendor_price', models.CharField(default='-', max_length=15)),
                ('vendor_phone_numbers', models.CharField(default='-', max_length=250)),
                ('vendor_followers_num', models.CharField(default='-', max_length=20)),
                ('vendor_following_num', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstaVendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='-', max_length=150)),
                ('vendor_link', models.CharField(default='-', max_length=255)),
                ('vendor_description', models.CharField(default='-', max_length=255)),
                ('vendor_category', models.CharField(default='-', max_length=50)),
                ('vendor_locations', models.CharField(default='-', max_length=255)),
                ('vendor_phone_numbers', models.CharField(default='-', max_length=250)),
                ('vendor_followers_num', models.CharField(default='-', max_length=20)),
                ('vendor_following_num', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_category', models.CharField(max_length=25)),
                ('vendor_category_tid', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='-', max_length=150)),
                ('vendor_link', models.CharField(default='-', max_length=255)),
                ('vendor_description', models.CharField(default='-', max_length=255)),
                ('vendor_category', models.CharField(default='-', max_length=50)),
                ('vendor_locations', models.CharField(default='-', max_length=255)),
                ('vendor_price', models.CharField(default='-', max_length=15)),
                ('vendor_phone_numbers', models.CharField(default='-', max_length=250)),
            ],
        ),
    ]
