# Generated by Django 5.0.6 on 2024-10-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instavendorinfo',
            name='vendor_price',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='vendorinfo',
            name='vendor_followers_num',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorinfo',
            name='vendor_following_num',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
