# Generated by Django 5.0.6 on 2024-11-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_scraper', '0002_instavendorinfo_vendor_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allvendorinfo',
            options={'verbose_name': 'All Vendor', 'verbose_name_plural': 'All Vendors'},
        ),
        migrations.AlterModelOptions(
            name='instavendorinfo',
            options={'verbose_name': 'Instagram Vendor', 'verbose_name_plural': 'Instagram Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'verbose_name': 'Vendor Category', 'verbose_name_plural': 'Vendor Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendorinfo',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='vendor_category',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='vendor_category_tid',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
